version: 0.2

phases:
  pre_build:
    commands:
      - $(aws ecr get-login --no-include-email --region eu-west-2)
  build:
    commands:
      - docker build -t test-demo:latest .
      - docker tag test-demo 634966137286.dkr.ecr.eu-west-2.amazonaws.com/test-demo:latest
  post_build:
    commands:
      - docker push 634966137286.dkr.ecr.eu-west-2.amazonaws.com/test-demo:latest
      - printf '[{"name":spark-backends,"imageUri":"%s"}]' 634966137286.dkr.ecr.eu-west-2.amazonaws.com/test-demo:latest > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
